name: hai

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          workflow_id: 'Your Workflow ID'
          token: ${{ secrets.GITHUB_TOKEN }}
